// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/iot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordedAt    string                 `protobuf:"bytes,1,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	UsageOverall  float32                `protobuf:"fixed32,2,opt,name=usage_overall,json=usageOverall,proto3" json:"usage_overall,omitempty"`
	FridgeKw      float32                `protobuf:"fixed32,3,opt,name=fridge_kw,json=fridgeKw,proto3" json:"fridge_kw,omitempty"`
	DishwasherKw  float32                `protobuf:"fixed32,4,opt,name=dishwasher_kw,json=dishwasherKw,proto3" json:"dishwasher_kw,omitempty"`
	FurnaceKw     float32                `protobuf:"fixed32,5,opt,name=furnace_kw,json=furnaceKw,proto3" json:"furnace_kw,omitempty"`
	Temperature   float32                `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Summary       string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementRequest) Reset() {
	*x = MeasurementRequest{}
	mi := &file_proto_iot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementRequest) ProtoMessage() {}

func (x *MeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementRequest.ProtoReflect.Descriptor instead.
func (*MeasurementRequest) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{0}
}

func (x *MeasurementRequest) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

func (x *MeasurementRequest) GetUsageOverall() float32 {
	if x != nil {
		return x.UsageOverall
	}
	return 0
}

func (x *MeasurementRequest) GetFridgeKw() float32 {
	if x != nil {
		return x.FridgeKw
	}
	return 0
}

func (x *MeasurementRequest) GetDishwasherKw() float32 {
	if x != nil {
		return x.DishwasherKw
	}
	return 0
}

func (x *MeasurementRequest) GetFurnaceKw() float32 {
	if x != nil {
		return x.FurnaceKw
	}
	return 0
}

func (x *MeasurementRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *MeasurementRequest) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *MeasurementRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type MeasurementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementResponse) Reset() {
	*x = MeasurementResponse{}
	mi := &file_proto_iot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementResponse) ProtoMessage() {}

func (x *MeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementResponse.ProtoReflect.Descriptor instead.
func (*MeasurementResponse) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{1}
}

func (x *MeasurementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MeasurementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_iot_proto protoreflect.FileDescriptor

const file_proto_iot_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/iot.proto\"\x93\x02\n" +
	"\x12MeasurementRequest\x12\x1f\n" +
	"\vrecorded_at\x18\x01 \x01(\tR\n" +
	"recordedAt\x12#\n" +
	"\rusage_overall\x18\x02 \x01(\x02R\fusageOverall\x12\x1b\n" +
	"\tfridge_kw\x18\x03 \x01(\x02R\bfridgeKw\x12#\n" +
	"\rdishwasher_kw\x18\x04 \x01(\x02R\fdishwasherKw\x12\x1d\n" +
	"\n" +
	"furnace_kw\x18\x05 \x01(\x02R\tfurnaceKw\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\a \x01(\x02R\bhumidity\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\"I\n" +
	"\x13MeasurementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2M\n" +
	"\rSensorService\x12<\n" +
	"\x0fSaveMeasurement\x12\x13.MeasurementRequest\x1a\x14.MeasurementResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_iot_proto_rawDescOnce sync.Once
	file_proto_iot_proto_rawDescData []byte
)

func file_proto_iot_proto_rawDescGZIP() []byte {
	file_proto_iot_proto_rawDescOnce.Do(func() {
		file_proto_iot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iot_proto_rawDesc), len(file_proto_iot_proto_rawDesc)))
	})
	return file_proto_iot_proto_rawDescData
}

var file_proto_iot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_iot_proto_goTypes = []any{
	(*MeasurementRequest)(nil),  // 0: MeasurementRequest
	(*MeasurementResponse)(nil), // 1: MeasurementResponse
}
var file_proto_iot_proto_depIdxs = []int32{
	0, // 0: SensorService.SaveMeasurement:input_type -> MeasurementRequest
	1, // 1: SensorService.SaveMeasurement:output_type -> MeasurementResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iot_proto_init() }
func file_proto_iot_proto_init() {
	if File_proto_iot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iot_proto_rawDesc), len(file_proto_iot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iot_proto_goTypes,
		DependencyIndexes: file_proto_iot_proto_depIdxs,
		MessageInfos:      file_proto_iot_proto_msgTypes,
	}.Build()
	File_proto_iot_proto = out.File
	file_proto_iot_proto_goTypes = nil
	file_proto_iot_proto_depIdxs = nil
}
